CREATE DATABASE MONISHKA_ASSIGNMENT;
USE MONISHKA_ASSIGNMENT;
CREATE TABLE STUDENT (
    USN VARCHAR(20) PRIMARY KEY,
    SName VARCHAR(50),
    Address VARCHAR(100),
    Phone VARCHAR(15),
    Gender CHAR(1)
);
CREATE TABLE SEMSEC (
    SSID VARCHAR(10) PRIMARY KEY,
    Sem INT,
    Sec CHAR(1)
);
CREATE TABLE CLASS (
    USN VARCHAR(20),
    SSID VARCHAR(10),
    PRIMARY KEY (USN, SSID),
    FOREIGN KEY (USN) REFERENCES STUDENT(USN),
    FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID)
);
CREATE TABLE SUBJECT (
    Subcode VARCHAR(10) PRIMARY KEY,
    Title VARCHAR(50),
    Sem INT,
    Credits INT
);
CREATE TABLE IAMARKS (
    USN VARCHAR(20),
    Subcode VARCHAR(10),
    SSID VARCHAR(10),
    Test1 INT,
    Test2 INT,
    Test3 INT,
    FinalIA INT,
    PRIMARY KEY (USN, Subcode, SSID),
    FOREIGN KEY (USN) REFERENCES STUDENT(USN),
    FOREIGN KEY (Subcode) REFERENCES SUBJECT(Subcode),
    FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID)
);
CREATE TABLE DEPARTMENT (
    Dno INT PRIMARY KEY,
    Dname VARCHAR(50),
    Mgrssn VARCHAR(20),
    Mgrstartdate DATE
);
CREATE TABLE EMPLOYEE (
    SSN VARCHAR(20) PRIMARY KEY,
    Name VARCHAR(50),
    Address VARCHAR(100),
    Sex CHAR(1),
    Salary DECIMAL(10,2) NOT NULL,
    Superssn VARCHAR(20),
    Dno INT,
    FOREIGN KEY (Superssn) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dno)
);
CREATE TABLE DLOCATION (
    Dno INT,
    Dloc VARCHAR(50),
    PRIMARY KEY (Dno, Dloc),
    FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dno)
);
CREATE TABLE PROJECT (
    PNo INT PRIMARY KEY,
    PName VARCHAR(50),
    PLocation VARCHAR(50),
    DNo INT,
    FOREIGN KEY (DNo) REFERENCES DEPARTMENT(Dno)
);
CREATE TABLE WORKS_ON (
    SSN VARCHAR(20),
    PNo INT,
    Hours DECIMAL(5,2),
    PRIMARY KEY (SSN, PNo),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNo) REFERENCES PROJECT(PNo)
);

CREATE TABLE CUSTOMER (
    Cust_id INT PRIMARY KEY,
    cust_name VARCHAR(50)
);
CREATE TABLE ITEM (
    item_id INT PRIMARY KEY,
    item_name VARCHAR(50),
    price INT NOT NULL
);
CREATE TABLE SALE (
    bill_no INT,
    bill_date DATE,
    cust_id INT,
    item_id INT,
    qty_sold INT,
    PRIMARY KEY (bill_no, item_id),
    FOREIGN KEY (cust_id) REFERENCES CUSTOMER(Cust_id),
    FOREIGN KEY (item_id) REFERENCES ITEM(item_id)
);
ALTER TABLE STUDENT
ADD Email VARCHAR(50);
USE MONISHKA_ASSIGNMENT;
ALTER TABLE STUDENT
ADD Email VARCHAR(50);
DESC STUDENT;
CREATE TABLE ITEM (
    item_id INT PRIMARY KEY,
    item_name VARCHAR(50),
    price INT NOT NULL
);
ALTER TABLE STUDENT
RENAME COLUMN SName TO StudentName;
DROP TABLE DLOCATION;
SHOW TABLES;
DESC STUDENT;