CREATE DATABASE MONISHKA_LABSHEET2;
USE MONISHKA_LABSHEET2;
CREATE TABLE CLASS (
    ID INT,
    NAME VARCHAR (20)
);
INSERT INTO CLASS VALUES (1, 'Bravo');
INSERT INTO CLASS VALUES (2, 'Alex');
INSERT INTO CLASS VALUES (4, 'Cheng');
COMMIT;
CREATE TABLE EMPLOYEES (
    Employee_Id INT PRIMARY KEY,
    First_Name VARCHAR(50),
    Last_Name VARCHAR(50),
    Email VARCHAR(100),
    Phone_Number VARCHAR(20),
    Hire_Date DATE,
    Job_Id VARCHAR(50),
    Salary DECIMAL(10,2),
    Commission_Pct DECIMAL(5,2),
    Manager_Id INT,
    Department_Id INT
);
CREATE TABLE Client_master (
    ClientNO VARCHAR(10) PRIMARY KEY,
    Name VARCHAR(50),
    City VARCHAR(50),
    bal_due DECIMAL(10,2)
);
RENAME TABLE Client_master TO Client12;
SELECT bal_due AS BALANCE
FROM Client12;
INSERT INTO CLASS VALUES (5,'Rahul');
COMMIT;
SET AUTOCOMMIT = 0;
SET SQL_SAFE_UPDATES = 0;
UPDATE CLASS SET Name = 'Abhijeet' WHERE ID = 5;
SELECT* FROM CLASS;
SAVEPOINT A;
INSERT INTO CLASS VALUES (6,'Chris');
SAVEPOINT B;
INSERT INTO CLASS VALUES (7,'Bravo');
SAVEPOINT C;
SELECT * FROM CLASS;
ROLLBACK TO B;
SELECT * FROM CLASS;
ROLLBACK TO A;
SELECT * FROM CLASS;
